# Generated by Django 4.1.7 on 2023-03-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devmanager', '0002_address_devices_devstatus_iaccess_province_techs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencies', models.CharField(max_length=45, verbose_name='Dependencia')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_address', to='devmanager.address')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'db_table': 'Dependencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations', models.TextField()),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'Movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_type', models.CharField(max_length=45, verbose_name='Tipo de Movimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'Tipo de Movimiento',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ['id'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='devusers',
            options={'ordering': ['id'], 'verbose_name': 'Usuario de Dispositivos', 'verbose_name_plural': 'Usuarios de Dispositivos'},
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='i_access',
            new_name='user_i_access',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='img',
        ),
        migrations.RemoveField(
            model_name='office',
            name='address',
        ),
        migrations.RemoveField(
            model_name='office',
            name='floor',
        ),
        migrations.AlterField(
            model_name='ip',
            name='i_access',
            field=models.CharField(max_length=1, verbose_name='internet_access'),
        ),
        migrations.AlterModelTable(
            name='devices',
            table='Dispositivos',
        ),
        migrations.AlterModelTable(
            name='devusers',
            table='UsuarioDispositivos',
        ),
        migrations.DeleteModel(
            name='IAccess',
        ),
        migrations.AddField(
            model_name='movments',
            name='mov_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movments_mov_type', to='devmanager.movtype'),
        ),
        migrations.AddField(
            model_name='movments',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movments_techs', to='devmanager.techs'),
        ),
        migrations.AddField(
            model_name='office',
            name='dependencies',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='office_dependency', to='devmanager.dependencies'),
            preserve_default=False,
        ),
    ]
