# Generated by Django 4.1.7 on 2023-03-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devmanager', '0003_dependencies_movments_movtype_alter_devices_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='dev_type',
        ),
    ]
